### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#28]
![screen shot 2016-09-06 at 11 17 12 am](https://cloud.githubusercontent.com/assets/15096099/18279427/8a716844-7423-11e6-8323-62570055ce36.png)

**Comment by bikash02** [comment]
You are getting the message due to "mixed content" . When an HTTPS page has HTTP content, we call that content “mixed”. Don’t worry about it.The Icon with gray alert means "Mixed content is blocked: secure" 
![screenshot-support mozilla org 2016-09-08 14-21-44](https://cloud.githubusercontent.com/assets/16361011/18343114/a3f5de00-75cf-11e6-9d0c-2ffe5b61f362.png)
