### ISSUE TITLE
Share links all seem to be working well. The styling could betightened up a bit on the + link. 

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/fundthisministry#34]

**Comment by i-puspita** [comment]
Solved. Please check.

**Comment by bikash02** [comment]
@camerontrimble please check https://www.fundthisministry.org/project/view/atlanta-dinner-church

**Comment by bikash02** [comment]
@amyolrick Please check the + link

**Comment by amyolrick** [comment]
Thanks, it's looking better. I still feel like it needs some work, though, and am attaching a few screenshots so you can see what I am seeing. 
- If  possible, it would be ideal to have the project image set to 100% so that it always matches the length of the div box that holds the social links. 
  ![screen shot 2016-10-25 at 8 59 14 am](https://cloud.githubusercontent.com/assets/22732566/19687195/88565426-9a92-11e6-88e0-ae5463733bae.png)
- I would recommend scaling down the social icons as well, so that they are a little smaller on the full screen, and pull in more quickly so that there is never a screen size where one icon bumps down to the second row. 
  ![screen shot 2016-10-25 at 8 59 24 am](https://cloud.githubusercontent.com/assets/22732566/19687196/885b827a-9a92-11e6-80c0-741a401d422c.png)
- Also, in the mobile screen the icons are not centered underneath the image. Can this be adjusted?
  ![screen shot 2016-10-25 at 8 59 33 am](https://cloud.githubusercontent.com/assets/22732566/19687194/88553154-9a92-11e6-9f93-542f4f306b5b.png)

Thank you for all of your work!!

**Comment by bikash02** [comment]
@i-puspita Please take a look and fix the issues asap.

**Comment by i-puspita** [comment]
The issues have been resolved. Please check.
